### ISSUE TITLE
Missing chalk dependency

### ISSUE THREAD

**Issue by fraxken** [bnb/bitandbang#1]
Hi,

Chalk is missing from dependencies:
```
λ npx bitandbang
npx: installed 1 in 2.549s
Cannot find module 'chalk'
```

Best Regards,
Thomas

**Comment by bnb** [comment]
hmm, this seems to be on the npx side – I can't reproduce at all  🤔 
![image](https://user-images.githubusercontent.com/502396/50238970-a2dd9b80-0375-11e9-9022-179ce51e08df.png)

**Comment by fraxken** [comment]
Fixed in your commits in November (i opened my issue before^^). Chalk was not in your `package.json` file.
