### ISSUE TITLE
npm ERR! code E404

### ISSUE THREAD

**Issue by mohamedmehdigara** [bnb/bitandbang#24]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@bnb%2fcard - Not found
npm ERR! 404 
npm ERR! 404  '@bnb/card@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2021-08-22T13_02_56_591Z-debug.log
L'installation de [ '@bnb/card@latest' ] a échoué avec le code 1

**Comment by bnb** [comment]
should be fixed now :)
