### ISSUE TITLE
Thanks for a clean antipattern of using node.js and npm

### ISSUE THREAD

**Issue by jehy** [bnb/bitandbang#6]
That's a wonderful example of misusing npm, node.js and Javascript.

This package contains 39 dependencies and 400kb (and 1.2 MB megabytes when unpacked to disk) of data. And all it does it making a small card in console.

Of cause, that project is more of o joke than a production code but it clearly shows why many developers despice JS, npm, Node.js and all ecosystem around it.

It could be much better if a bundler was added to remove all extra deps and make tree shake.

**Comment by bnb** [comment]
k thx
